[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_twitter = "4Hto2zMr9u6z2maCnmQ8US3r1aXrPBD8fF4ZYTTVdeuq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/mono/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
mono-script = "echo 'Hello Mono!'"